name: My CI

on: [push]

jobs:

  job1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: while true; do foo; sleep 2; done
      env:
        # HI: ${{ secrets.HI }}
  job2:
    runs-on: ubuntu-latest
    needs: ['job1']
    steps:
    - run: echo Step 2
  job3:
    runs-on: ubuntu-latest
    needs: ['job1', 'job2']
    steps:
    - run: echo Step 3
