name: My CI

on: [push]

jobs:

  job1:
    runs-on: ubuntu-latest
    steps:
    - run: echo Step 1
  job2:
    runs-on: ubuntu-latest
    needs: ['job1']
    steps:
    - run: echo Step2
  job3:
    runs-on: ubuntu-latest
    needs: ['job1', 'job2']
    steps:
    - run: echo Step3
