name: End To End Tests

on: [push]

jobs:
  install:
    name: "Test Installation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: ./install.sh
      - run: wflow
  npm-install:
    name: "Test NPM Installation"
    runs-on: ubuntu-latest
    steps:
      - run: sudo npm install -g wflow
      - run: wflow -f /usr/lib/node_modules/wflow/workflows/parallel.yml
